### ISSUE TITLE
theano error when trying img-img mode

### ISSUE THREAD

**Issue by emoebel** [ELEKTRONN/ELEKTRONN#3]
Hi, here I am again.

I'm trying out the img-img mode, and get following error when trying to run elektronn-train : 

```
.
.
.
Compiling SGD
 Compiling done  - in 103.051 s!
Traceback (most recent call last):
  File "/fs/pool/pool-bmapps/hpcl5/app/soft/PYTHON/2.7.9/lib/python2.7/site-packages/elektronn/training/trainer.py", line 180, in run
    nll, nll_instance, t_per_train = cnn.trainingStep(*batch, mode=config.optimizer)  # Update step
  File "/fs/pool/pool-bmapps/hpcl5/app/soft/PYTHON/2.7.9/lib/python2.7/site-packages/elektronn/net/convnet.py", line 822, in trainingStep
    loss, loss_instance = self.SGD(*args)
  File "/fs/pool/pool-bmapps/hpcl5/app/soft/PYTHON/2.7.9/lib/python2.7/site-packages/elektronn/net/optimizer.py", line 140, in __call__
    ret = list(self.step(*args))
  File "/fs/pool/pool-bmapps/hpcl5/app/soft/PYTHON/2.7.9/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/fs/pool/pool-bmapps/hpcl5/app/soft/PYTHON/2.7.9/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
AssertionError: Theano Assert failed!
Apply node that caused the error: Assert(Elemwise{eq,no_inplace}.0, Elemwise{eq,no_inplace}.0, Elemwise{eq,no_inplace}.0, Elemwise{eq,no_inplace}.0)
Inputs types: [TensorType(int8, 5D), TensorType(int8, scalar), TensorType(int8, scalar), TensorType(int8, scalar)]
Inputs shapes: [(1, 2, 5, 5, 5), (), (), ()]
Inputs strides: [(250, 125, 25, 5, 1), (), (), ()]
Inputs values: ['not shown', array(0, dtype=int8), array(0, dtype=int8), array(0, dtype=int8)]
```

For simplicity I used same size for input images and output images, as I believe that elektronn adjusts the sizes internally. Attached you can find my config file and the complete output.
[img-img_error.zip](https://github.com/ELEKTRONN/ELEKTRONN/files/176661/img-img_error.zip)

Any idea what I am missing?

**Comment by emoebel** [comment]
Okay I found where my error was. In the config file, I wanted to define the ReLu activation for every layer, so I put : 
`activation_func = ['relu']`

But elektronn-train interpreted somehow that there is only one layer in my network (because I gave a list object that contains 1 element) and this clashed with the rest of my config, where I defined 3 layers in total.

So the solution is not to give a list object, but simply a string:
`activation_func = 'relu'`
Defining the param for each layer works also of course:
`activation_func = ['relu', 'relu', 'relu']`

But mixing both syntaxes was not a good idea. Now it works again :-)
